from __future__ import annotations

import argparse
import json
from pathlib import Path


def _load(path: str) -> dict | None:
    p = Path(path)
    if not p.exists():
        return None
    return json.loads(p.read_text())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metrics", default="reports/metrics.json")
    parser.add_argument("--out", default="reports/metrics_summary.md")
    args = parser.parse_args()

    metrics = json.loads(Path(args.metrics).read_text())
    nocache = _load("reports/metrics_nocache.json")
    redis = _load("reports/metrics_redis.json")

    lines = [
        "# Day 10 Reliability — Auto-generated Metrics Summary",
        "",
        "_Generated by `scripts/generate_report.py` from the chaos metrics JSON._",
        "_The graded narrative lives in `reports/final_report.md`._",
        "",
        "## Metrics Summary (with in-memory cache)",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]
    for key, value in metrics.items():
        if key == "scenarios":
            continue
        lines.append(f"| {key} | {value} |")

    lines += ["", "## Chaos Scenarios", "", "| Scenario | Status |", "|---|---|"]
    for key, value in metrics.get("scenarios", {}).items():
        lines.append(f"| {key} | {value} |")

    if nocache or redis:
        lines += [
            "",
            "## Backend Comparison",
            "",
            "| Metric | No cache | Memory cache | Redis cache |",
            "|---|---:|---:|---:|",
        ]
        for key in ("availability", "cache_hit_rate", "estimated_cost", "circuit_open_count"):
            row = [
                str(nocache.get(key)) if nocache else "-",
                str(metrics.get(key)),
                str(redis.get(key)) if redis else "-",
            ]
            lines.append(f"| {key} | {row[0]} | {row[1]} | {row[2]} |")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
